timestamp_col: Time(secs)
fridge: 'oxicold'
metrics:
  PressureM1Condense(Bar):
    field: pressure
    tags:
      channel: M1
      location: condense
    scaling: 1e3
  PressureM3Tank(Bar):
    field: pressure
    tags:
      channel: M3
      location: tank
    scaling: 1e3
  PressureFPSafety(Bar):
    field: pressure
    tags:
      location: forepump-safety
    scaling: 1e3
  Still (mbar):
    field: pressure
    tags:
      channel: M21
      location: still
  Forepump (mbar):
    field: pressure
    tags:
      channel: M22
      location: forepump
  Dewar (mbar):
    field: pressure
    tags:
      channel: MV
      location: ovc
  Input Water Temp:
    field: cpatempwi
  Output Water Temp:
    field: cpatempwo
  Helium Temp:
    field: cpatemph
  Oil Temp:
    field: cpatempo
  Motor Current:
    field: cpacurrent
  PT2 Head T(K):
    field: temperature
    tags:
      location: PT2-head
  PT2 Plate T(K):
    field: temperature
    tags:
      location: PT2-plate
  Still T(K):
    field: temperature
    tags:
      location: still
  100mK Plate T(K):
    field: temperature
    tags:
      location: 100mK-plate
  MC Cernox T(K):
    field: temperature
    tags:
      location: MXC-cernox
  MC Generic RuO2 T(K):
    field: temperature
    tags:
      location: MXC-ruox
  PT1 Head T(K):
    field: temperature
    tags:
      location: PT1-head
  PT1 Plate T(K):
    field: temperature
    tags:
      location: PT1-plate
  Still heater (W):
    field: heater_power
    tags:
      location: still
  chamber heater (W):
    field: heater_power
    tags:
      location: chamber

